# https://goframe.org/docs/web/server-config-file-template
server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# https://goframe.org/docs/core/glog-config
logger:
  level: "all"
  stdout: true

ds_think_chat_model:
  api_key: "xxxxxx"
  base_url: "https://ark.cn-beijing.volces.com/api/v3"
  model: "deepseek-v3-1-terminus"

ds_quick_chat_model:
  api_key: "xxxxxx"
  base_url: "https://ark.cn-beijing.volces.com/api/v3"
  model: "deepseek-v3-1-terminus"

doubao_embedding_model:
  api_key: "835e2da6-579d-459f-8818-8d48a7431541"
  model: "doubao-embedding"


file_dir: "/你的路径/SuperBizAgent/internal/ai/cmd/knowledge_cmd/docs"

